export const donationCompatibility = [{type: "A+",to: "A+, AB+",from :"A+, A-, O+, O-"},{type: "O+",to: "O+, A+, B+, AB+",from :"O+, O-"},{type: "B+",to: "B+, AB+",from :"B+, B-, O+,O-"},{type: "AB+",to: "AB+",from :"Everyone"},{type: "A-",to: "A+, A-, AB+, AB-",from :"A-, O-"},{type: "O-",to: "Everyone",from :"O-"},{type: "B-",to: "B+, B-, AB+,AB-",from :"B-, O-"},{type: "AB-",to: "AB-, AB+",from :"AB-, A-, B-, O-"},];
export const FAQanswers = {
    "white-blood": ["Blood Collected straight from the donor after its donation usually separated into red blood cells, platelets, and plasma.", "You need to be 18-65 years old, weigh 45kg or more and be fit and healthy.", "Stomach disease, kidney disease, childbirth, operations, blood loss, trauma, cancer, blood diseases, haemophilia, anemia, heart disease.", "Red cells can be stored for 42 days." , "15 minutes to donate", "Every 12 weeks"],
    plasma: ["The straw-coloured liquid in which red blood cells, white blood cells, and platelets float in.Contains special nutrients which can be used to create 18 different type of medical products to treat many different medical conditions.", "You need to be 18-70 (men) or 20-70 (women) years old, weigh 50kg or more and must have given successful whole blood donation in last two years.", "Immune system conditions, pregnancy (including anti-D injections), bleeding, shock, burns, muscle and nerve conditions, haemophilia, immunisations.", "Plasma can last up to one year when frozen.", "15 minutes to donate.", "Every 2-3 weeks." ],
    platelet:["The tiny 'plates' in blood that wedge together to help to clot and reduce bleeding. Always in high demand, Vital for people with low platelet count, like malaria and cancer patients.", "You need to be 18-70 years old (men), weigh 50kg or more and have given a successful plasma donation in the past 12 months", "Cancer, blood diseases, haemophilia, anaemia, heart disease, stomach disease, kidney disease, childbirth, operations, blood loss, trauma, burns.", "Just five days..", "45 minutes to donate.", "Every 2 weeks"],
}

export const userList = [
	{
		"name": "Kasimir Byrd",
		"state": "Uganda",
		"city": "Montbliart",
		"conatct": "16180430 0034",
		"dob": "28-05-22",
        "bloodGroup": "AB+",
	},
	{
		"name": "Chandler Melendez",
		"state": "Tanzania",
		"city": "Hillsboro",
		"conatct": "16021209 0914",
		"dob": "12-10-20",
        "bloodGroup": "A+",
	},
	{
		"name": "Louis Gutierrez",
		"state": "Chile",
		"city": "Ilhéus",
		"conatct": "16900508 0792",
		"dob": "04-05-21",
        "bloodGroup": "B-",
	},
	{
		"name": "Ashton Price",
		"state": "Libya",
		"city": "Hattiesburg",
		"conatct": "16340818 7957",
		"dob": "30-12-21",
        "bloodGroup": "AB+",
	},
	{
		"name": "Noah Ballard",
		"state": "Cuba",
		"city": "Traiskirchen",
		"conatct": "16551001 1553",
		"dob": "15-12-20",
        "bloodGroup": "A+",
	},
	{
		"name": "Lawrence Stark",
		"state": "Curaçao",
		"city": "Bionaz",
		"conatct": "16430912 9791",
		"dob": "02-02-21",
        "bloodGroup": "AB+",
	},
	{
		"name": "Cameron Payne",
		"state": "China",
		"city": "Perwez",
		"conatct": "16521108 9064",
		"dob": "13-10-20",
        "bloodGroup": "O+",
	},
	{
		"name": "Brennan Davenport",
		"state": "Belarus",
		"city": "Colchane",
		"conatct": "16910312 1316",
		"dob": "09-12-20",
        "bloodGroup": "B-",
	},
	{
		"name": "Jackson Witt",
		"state": "Tuvalu",
		"city": "Crystal Springs",
		"conatct": "16091123 2718",
		"dob": "10-02-22",
        "bloodGroup": "A+",
	},
	{
		"name": "Ralph Bernard",
		"state": "Montserrat",
		"city": "Bicester",
		"conatct": "16630325 9573",
		"dob": "21-12-20",
        "bloodGroup": "O-",
	},
	{
		"name": "Harding Suarez",
		"state": "Equatorial Guinea",
		"city": "Ozherelye",
		"conatct": "16760629 8219",
		"dob": "03-11-20",
        "bloodGroup": "O+",
	},
	{
		"name": "Nicholas Avila",
		"state": "Guyana",
		"city": "Qu�bec City",
		"conatct": "16270511 7162",
		"dob": "12-11-20",
        "bloodGroup": "A+",
	},
	{
		"name": "Bevis Mcdowell",
		"state": "Lesotho",
		"city": "Rimbey",
		"conatct": "16281210 4582",
		"dob": "18-09-20",
        "bloodGroup": "O+",
	},
	{
		"name": "Alan Fox",
		"state": "Tajikistan",
		"city": "Fortune",
		"conatct": "16341130 0225",
		"dob": "16-04-21"
	},
	{
		"name": "Colorado Espinoza",
		"state": "Ireland",
		"city": "Pontey",
		"conatct": "16501011 3586",
		"dob": "29-06-21",
        "bloodGroup": "A+",
	},
	{
		"name": "Erasmus Gamble",
		"state": "Philippines",
		"city": "Spresiano",
		"conatct": "16160418 6047",
		"dob": "08-12-21",
        "bloodGroup": "B+",
	},
	{
		"name": "Alfonso Schwartz",
		"state": "Tunisia",
		"city": "Alacant",
		"conatct": "16410805 3028",
		"dob": "01-11-21",
        "bloodGroup": "AB+",
	},
	{
		"name": "Hall Leon",
		"state": "Netherlands",
		"city": "Blevio",
		"conatct": "16310923 6657",
		"dob": "13-08-20",
        "bloodGroup": "O+",
	},
	{
		"name": "Igor Farmer",
		"state": "Chad",
		"city": "Palanzano",
		"conatct": "16480102 3880",
		"dob": "13-12-21",
        "bloodGroup": "B+",
	},
	{
		"name": "Chancellor Franks",
		"state": "Anguilla",
		"city": "Louisville",
		"conatct": "16991123 9714",
		"dob": "15-04-22",
        "bloodGroup": "AB-",
	},
	{
		"name": "Todd Daniel",
		"state": "Jersey",
		"city": "Hull",
		"conatct": "16661014 4880",
		"dob": "16-04-22",
        "bloodGroup": "AB+",
	},
];